version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - yum install zip -y
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - zip -r folder1.zip /folder1
    post_build:
        commands:
            - echo "we are in the post build phase"
artifacts:
    files:
      - '**/*.zip'
    
